# Generated by Django 5.0.1 on 2024-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('hospital', 'Hospital'), ('association', 'Association')], max_length=20),
        ),
    ]
