# Generated by Django 5.0.1 on 2024-05-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alertes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('typeDeSang', models.CharField(max_length=100)),
                ('niveauGravite', models.CharField(default='faible', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
