# Generated by Django 5.0.1 on 2024-05-05 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alertes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
