# Generated by Django 5.0.1 on 2024-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alertes', '0002_alertes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertes',
            name='date',
            field=models.DateTimeField(default='2024-05-05T19:34:08.840799+00:00'),
        ),
    ]
